// Social Media Calendar Pro — Sample Data
// Dados de exemplo para demonstração da plataforma

import { Client, Post } from "./types";

export const SAMPLE_CLIENTS: Client[] = [
  {
    id: "c1",
    name: "Bella Estética",
    brandColor: "#E91E8C",
    brandColorSecondary: "#FF6EC7",
    logoInitials: "BE",
    industry: "Beleza & Estética",
    instagramHandle: "@bellastetica",
    active: true,
  },
  {
    id: "c2",
    name: "TechFlow",
    brandColor: "#2563EB",
    brandColorSecondary: "#60A5FA",
    logoInitials: "TF",
    industry: "Tecnologia",
    instagramHandle: "@techflow.br",
    active: true,
  },
  {
    id: "c3",
    name: "Sabor & Arte",
    brandColor: "#D97706",
    brandColorSecondary: "#FCD34D",
    logoInitials: "SA",
    industry: "Gastronomia",
    instagramHandle: "@saborarte",
    active: true,
  },
  {
    id: "c4",
    name: "FitLife",
    brandColor: "#059669",
    brandColorSecondary: "#34D399",
    logoInitials: "FL",
    industry: "Fitness & Saúde",
    instagramHandle: "@fitlife.oficial",
    active: true,
  },
  {
    id: "c5",
    name: "Casa & Decor",
    brandColor: "#7C3AED",
    brandColorSecondary: "#A78BFA",
    logoInitials: "CD",
    industry: "Decoração",
    instagramHandle: "@casadecor.br",
    active: true,
  },
  {
    id: "c6",
    name: "Moda Única",
    brandColor: "#DC2626",
    brandColorSecondary: "#FCA5A5",
    logoInitials: "MU",
    industry: "Moda & Lifestyle",
    instagramHandle: "@modaunica",
    active: true,
  },
];

export const SAMPLE_POSTS: Post[] = [
  // Bella Estética
  {
    id: "p1",
    clientId: "c1",
    title: "Promoção Dia das Mães",
    description: "Post promocional para o pacote especial Dia das Mães. Destacar os serviços inclusos: manicure, pedicure e massagem relaxante. Usar paleta rosa com elementos florais.",
    type: "feed",
    status: "pronto",
    dayOfWeek: "seg",
    scheduledTime: "09:00",
    driveLink: "https://drive.google.com/drive/folders/exemplo1",
    caption: "Presenteie quem você ama com um dia de cuidados especiais 💕 Pacote Dia das Mães com 30% OFF!",
    hashtags: "#diaDasMaes #beleza #estetica #promoção #manicure",
    notes: "Aprovado pela cliente em 20/02",
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-20T14:30:00Z",
  },
  {
    id: "p2",
    clientId: "c1",
    title: "Tutorial Nail Art",
    description: "Reels mostrando passo a passo de nail art primavera. Duração: 30-45 segundos. Música trending do momento.",
    type: "reels",
    status: "em_producao",
    dayOfWeek: "qua",
    scheduledTime: "18:00",
    driveLink: "https://drive.google.com/drive/folders/exemplo2",
    caption: "Aprenda essa nail art incrível em casa! 💅✨",
    hashtags: "#nailart #unhas #tutorial #beleza",
    notes: "Aguardando gravação do vídeo",
    createdAt: "2026-02-05T10:00:00Z",
    updatedAt: "2026-02-22T09:00:00Z",
  },
  {
    id: "p3",
    clientId: "c1",
    title: "Stories: Agenda da Semana",
    description: "Stories mostrando os horários disponíveis para agendamento na semana. Incluir link de agendamento online.",
    type: "stories",
    status: "rascunho",
    dayOfWeek: "seg",
    scheduledTime: "08:00",
    notes: "Criar template no Canva",
    createdAt: "2026-02-10T10:00:00Z",
    updatedAt: "2026-02-10T10:00:00Z",
  },
  // TechFlow
  {
    id: "p4",
    clientId: "c2",
    title: "Lançamento App v2.0",
    description: "Post de lançamento da nova versão do aplicativo. Destacar as 5 principais funcionalidades novas. Design tech e moderno.",
    type: "feed",
    status: "pronto",
    dayOfWeek: "ter",
    scheduledTime: "10:00",
    driveLink: "https://drive.google.com/drive/folders/exemplo3",
    caption: "A revolução chegou! TechFlow App 2.0 está aqui 🚀",
    hashtags: "#tech #app #inovação #tecnologia #startup",
    notes: "Coordenar com equipe de marketing",
    createdAt: "2026-02-08T10:00:00Z",
    updatedAt: "2026-02-23T16:00:00Z",
  },
  {
    id: "p5",
    clientId: "c2",
    title: "LinkedIn: Case de Sucesso",
    description: "Artigo no LinkedIn sobre o case de sucesso do cliente Empresa X. Métricas de crescimento e depoimento.",
    type: "linkedin",
    status: "em_producao",
    dayOfWeek: "qui",
    scheduledTime: "08:00",
    driveLink: "https://drive.google.com/drive/folders/exemplo4",
    notes: "Aguardando aprovação do cliente para publicar métricas",
    createdAt: "2026-02-12T10:00:00Z",
    updatedAt: "2026-02-21T11:00:00Z",
  },
  {
    id: "p6",
    clientId: "c2",
    title: "Carrossel: 5 Tendências Tech 2026",
    description: "Carrossel educativo sobre as 5 maiores tendências de tecnologia para 2026. Infográficos modernos.",
    type: "carrossel",
    status: "pronto",
    dayOfWeek: "sex",
    scheduledTime: "12:00",
    driveLink: "https://drive.google.com/drive/folders/exemplo5",
    caption: "O futuro é agora! Conheça as 5 tendências que vão dominar 2026 👇",
    hashtags: "#tecnologia #tendencias #futuro #inovacao #tech2026",
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-02-23T10:00:00Z",
  },
  // Sabor & Arte
  {
    id: "p7",
    clientId: "c3",
    title: "Receita: Bolo de Limão",
    description: "Reels com receita rápida de bolo de limão siciliano. Mostrar o processo completo em 60 segundos.",
    type: "reels",
    status: "publicado",
    dayOfWeek: "seg",
    scheduledTime: "12:00",
    driveLink: "https://drive.google.com/drive/folders/exemplo6",
    caption: "Esse bolo de limão vai te conquistar! 🍋 Receita completa nos comentários",
    hashtags: "#receita #bolo #limao #gastronomia #foodie",
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-17T12:00:00Z",
  },
  {
    id: "p8",
    clientId: "c3",
    title: "Menu Especial Fim de Semana",
    description: "Post apresentando o menu especial do fim de semana. Fotos dos pratos principais com preços.",
    type: "feed",
    status: "em_producao",
    dayOfWeek: "sex",
    scheduledTime: "11:00",
    driveLink: "https://drive.google.com/drive/folders/exemplo7",
    notes: "Aguardando fotos dos novos pratos",
    createdAt: "2026-02-18T10:00:00Z",
    updatedAt: "2026-02-22T14:00:00Z",
  },
  {
    id: "p9",
    clientId: "c3",
    title: "TikTok: Bastidores da Cozinha",
    description: "Vídeo mostrando os bastidores da cozinha, preparação dos pratos e equipe. Conteúdo autêntico.",
    type: "tiktok",
    status: "rascunho",
    dayOfWeek: "qua",
    scheduledTime: "19:00",
    notes: "Gravar na próxima semana",
    createdAt: "2026-02-20T10:00:00Z",
    updatedAt: "2026-02-20T10:00:00Z",
  },
  // FitLife
  {
    id: "p10",
    clientId: "c4",
    title: "Treino da Semana",
    description: "Carrossel com o treino completo da semana. 7 exercícios com instruções e repetições.",
    type: "carrossel",
    status: "pronto",
    dayOfWeek: "seg",
    scheduledTime: "06:00",
    driveLink: "https://drive.google.com/drive/folders/exemplo8",
    caption: "Sua semana de treinos está aqui! Salva esse post 💪🔥",
    hashtags: "#treino #fitness #academia #saude #workout",
    createdAt: "2026-02-10T10:00:00Z",
    updatedAt: "2026-02-23T08:00:00Z",
  },
  {
    id: "p11",
    clientId: "c4",
    title: "Reels: Transformação 30 dias",
    description: "Reels motivacional mostrando transformação de aluno em 30 dias. Depoimento e antes/depois.",
    type: "reels",
    status: "pronto",
    dayOfWeek: "qua",
    scheduledTime: "18:00",
    driveLink: "https://drive.google.com/drive/folders/exemplo9",
    caption: "30 dias de dedicação e olha o resultado! 🙌 Você também pode!",
    hashtags: "#transformacao #motivacao #fitness #resultado #treino",
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-02-23T09:00:00Z",
  },
  // Casa & Decor
  {
    id: "p12",
    clientId: "c5",
    title: "Tendências Decoração 2026",
    description: "Carrossel com as principais tendências de decoração para 2026. Paletas de cores, materiais e estilos.",
    type: "carrossel",
    status: "em_producao",
    dayOfWeek: "ter",
    scheduledTime: "10:00",
    driveLink: "https://drive.google.com/drive/folders/exemplo10",
    notes: "Designer finalizando os slides",
    createdAt: "2026-02-16T10:00:00Z",
    updatedAt: "2026-02-22T15:00:00Z",
  },
  {
    id: "p13",
    clientId: "c5",
    title: "Antes e Depois: Sala de Estar",
    description: "Post mostrando a transformação completa de uma sala de estar. Fotos profissionais do projeto.",
    type: "feed",
    status: "pronto",
    dayOfWeek: "qui",
    scheduledTime: "11:00",
    driveLink: "https://drive.google.com/drive/folders/exemplo11",
    caption: "Que transformação incrível! 😍 Sala de estar repaginada do zero",
    hashtags: "#decoracao #antesedepois #sala #interiores #design",
    createdAt: "2026-02-18T10:00:00Z",
    updatedAt: "2026-02-23T11:00:00Z",
  },
  // Moda Única
  {
    id: "p14",
    clientId: "c6",
    title: "Nova Coleção Outono",
    description: "Post de lançamento da coleção outono/inverno 2026. Fotos editoriais com modelos.",
    type: "feed",
    status: "rascunho",
    dayOfWeek: "sex",
    scheduledTime: "14:00",
    driveLink: "https://drive.google.com/drive/folders/exemplo12",
    notes: "Aguardando ensaio fotográfico",
    createdAt: "2026-02-20T10:00:00Z",
    updatedAt: "2026-02-20T10:00:00Z",
  },
  {
    id: "p15",
    clientId: "c6",
    title: "Stories: Enquete de Estilo",
    description: "Stories interativo com enquete sobre preferências de estilo para a nova coleção.",
    type: "stories",
    status: "pronto",
    dayOfWeek: "ter",
    scheduledTime: "15:00",
    driveLink: "https://drive.google.com/drive/folders/exemplo13",
    caption: "Qual estilo você prefere para o outono?",
    createdAt: "2026-02-21T10:00:00Z",
    updatedAt: "2026-02-23T10:00:00Z",
  },
  {
    id: "p16",
    clientId: "c6",
    title: "Reels: Look do Dia",
    description: "Reels rápido com look completo do dia. Mostrar peças, combinações e onde comprar.",
    type: "reels",
    status: "em_producao",
    dayOfWeek: "dom",
    scheduledTime: "10:00",
    notes: "Gravar com influenciadora parceira",
    createdAt: "2026-02-22T10:00:00Z",
    updatedAt: "2026-02-22T10:00:00Z",
  },
];
